a = int(input("Enter the Feet for the first piece of fabric: "))
b = int(input("Enter the Inches for the first piece of fabric: "))
x = int(input("Enter the Feet for the second piece of fabric: "))
y = int(input("Enter the Inches for the second piece of fabric: "))
c = str((a + x)+((int((b+y)/12))))
z = str(((((b+y)%12))))
print("Feet: " + c + " Inches: " + z)
